---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  data:
    .dockerconfigjson: {{ .Values.dockerConfigSecret.config }}
  kind: Secret
  metadata:
    name: dockerconfigjson
    labels: 
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
  type: kubernetes.io/dockerconfigjson